version: '3'
services:
  local-rag:
    container_name: local-rag
    build: 
      context: ./src
      dockerfile: ../.docker/Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - '8501:8501/tcp'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
